function [x, v, exitflag, output] = p1

opt = optimset(...
    optimset(@linprog), ...
    Display='iter', ...
    Algorithm='dual-simplex');

[x, v, exitflag, output] = linprog(...
    [-5; -3], ...
    [1, 2; 1, -2; 3, -1; 4, 2], ...
    [6; 2; 5; 8], ...
    [], [], ...
    [0; 0], [], ...
    opt);

end
